Refactor the entire pipeline.
biowdl/gatk-variantcalling pull request #18
Opened 2020-05-11 11:06 UTC by rhpvorderman

I wanted to be able to use a single-sample pipeline. So now I have refactored the pipeline to be imported into three parts
- calculate regions. Where you calculate the regions (in case you want to call with X-ploidy aware stuff). It also calculates the scatters.
- Do single sample calling. With given scatters.
- Do joint genotyping (optional, single sample has to be set to gvcf mode).

### Checklist
- [ ] Pull request details were added to CHANGELOG.md
- [ ] Documentation was updated (if required).

2020-05-11 13:52 UTC, DavyCats requested changes

2020-05-11 13:52 UTC, DavyCats commented on calculate-regions.wdl
>          YNonParRegions: {description: "Bed file with the non-PAR regions of Y", category: "required"}
```suggestion
        XNonParRegions: {description: "Bed file with the non-PAR regions of X", category: "common"}
        YNonParRegions: {description: "Bed file with the non-PAR regions of Y", category: "common"}
```

2020-05-11 13:52 UTC, DavyCats commented on docs/index.md
> +  optional. Requires the single sample pipeline to be run in GVCF mode.
Shouldn't this be outside of the codeblock?

2020-05-11 13:52 UTC, DavyCats commented on jointgenotyping.wdl
> +        gvcfFilesIndex: {description: "The indexes for the GVCF files."}
missing category

2020-05-11 13:52 UTC, DavyCats commented on single-sample-variantcalling.wdl
> +        gender: {description: "Gender of the sample. Accepted values: female,F,f,male,M,m. Other values default to 'unknown'."}
missing category

2020-05-12 06:18 UTC, rhpvorderman commented
@DavyCats Thanks! Issues have been resolved.

2020-05-12 08:12 UTC, DavyCats approved these changes

2020-05-12 08:18 UTC, merged